language: python
matrix:
  include:

    - os: osx
      python: "3.7"
      language: generic
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
      install: 
        - sudo pip install . -r requirements.txt

    - os: linux
      python: "3.7"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .

script:
    - make coverage
    - make lint
after_script:
    - pip3 install codecov
    - codecov