language: python
matrix:
  include:

    - os: linux
      python: "3.6"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.7"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.8"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.8-dev"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.9-dev"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "pypy3"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    
    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36'
      before_install:
        - sudo pip install setuptools
        - brew update
        - brew install openssl
        - brew install zlib
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv-virtualenv venv
        - source venv/bin/activate
        - python --version
      install:
        - python -m pip install -U pip
        - sudo pip install . -r requirements.txt

  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"

script:
    - make coverage
    - make lint
after_script:
    - pip3 install codecov
    - codecov