language: python
matrix:
  include:
    - python: "3.6"
    - python: "3.7"
    - python: "3.8"
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
      env: NO_MYPY=true
  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
      env: NO_MYPY=true
install:
    - pip install -r requirements.txt 
    - pip install pytest flake8 coverage
    - pip install .
script:
    - make coverage
    - make lint
after_script:
    - pip install codecov
    - codecov

