language: python
matrix:
  include:

    - os: linux
      python: "3.7"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    
    - os: osx
      language: generic
      env: PYTHON=3.6.9'
      before_install:
        - brew update
        - brew install openssl
        - brew install zlib
        - brew outdated pyenv || brew upgrade pyenv
        - brew install pyenv-virtualenv
        - pyenv install $PYTHON
        - export PYENV_VERSION=$PYTHON
        - export PATH="/Users/travis/.pyenv/shims:${PATH}"
        - pyenv-virtualenv venv
        - source venv/bin/activate
        - python --version
      install:
        - python -m pip install -U pip
        - sudo pip install setuptools
        - sudo pip install .

script:
    - make test
    - make coverage
    - make lint
after_script:
    - pip3 install codecov
    - codecov