language: python
matrix:
  include:

    - os: linux
      python: "3.6"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.7"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.8"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.8-dev"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "3.9-dev"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .
    - os: linux
      python: "pypy3"
      install:
        - pip3 install -r requirements.txt 
        - pip3 install -r test_requirements.txt
        - pip3 install .

  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"

script:
    - make coverage
    - make lint
after_script:
    - pip3 install codecov
    - codecov