language: python
matrix:
  include:
    - python: "3.6"
      os: osx
      os: linux
    - python: "3.7"
    - python: "3.8"
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
  allow_failures:
    - python: "3.8-dev"
    - python: "3.9-dev"
    - python: "pypy3"
before_install:
    - wget http://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh
        -O miniconda.sh
    - chmod +x miniconda.sh
    - "./miniconda.sh -b"
    - export PATH=~/miniconda3/bin/:$PATH
    - conda update --yes conda
install:
    - pip3 install -r requirements.txt 
    - pip3 install -r test_requirements.txt
    - pip3 install .
script:
    - make coverage
    - make lint
after_script:
    - pip3 install codecov
    - codecov